### PR TITLE
Expose the BoxFit value to a widget.

### PR DESCRIPTION
**Pull request by jigarfumakiya**
Hello @ch-muhammad-adil 

I have exposed BoxFit value to a widget. So dev can set BoxFit value as want.
Please check my PR and Let me know if require any changes.

Thanks for the great package.

### CODE REVIEW

**Comment by ch-muhammad-adil** [comment]
I will check it, thanks for PR.

**Comment by jigarfumakiya** [comment]
Hey @ch-muhammad-adil 
Any chance that you can merge this PR by end of this week.?

**Review by ch-muhammad-adil — APPROVED** [review]

**Comment by ch-muhammad-adil** [comment]
Hey Sorry, I have merged it and release it now.

**Comment by jigarfumakiya** [comment]
Thanks @ch-muhammad-adil

**Comment by ch-muhammad-adil** [comment]
You are welcome, and thanks for contributing. Latest release is having your
changes plus some more fixes.

**Pull request merged**
